<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit9dbc047c5f7038322952e0d9e630eb4c
{
    public static $prefixLengthsPsr4 = array (
        'D' => 
        array (
            'DankiCode\\' => 10,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'DankiCode\\' => 
        array (
            0 => __DIR__ . '/../..' . '/DankiCode',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit9dbc047c5f7038322952e0d9e630eb4c::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit9dbc047c5f7038322952e0d9e630eb4c::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
